### ISSUE TITLE
Getting Started - BloodHound cannot click Login button

### ISSUE THREAD

**Issue by matchstickboy** [BloodHoundAD/BloodHound#186]
Hello,

Very sorry if I am repeating an issue, but after following the Getting Started setup instructions for Windows I am unable to click on the BloodHound login button.

System Environment:
Java 8.171
Neo4J Community 3.4.1
BloodHound 1.5.2
OS:  Windows 7 x64

I am able to follow all instructions successfully including initial setup of Neo4J (installing as a service, changing initial password for the Neo4J user).  I am also able to copy the Bloodhound database into the target directory of the Neo4J program folder, and update the .conf file as needed.  Just can't click on the Login button.

I could easily be missing something, but can't figure out what it is.  Any help or suggestions would be appreciated.

Thank you in advance.

Chris

**Comment by JED1SEN7INEL** [comment]
Launching bloodhound.exe as admin worked for me. Prior to that, I was experiencing the same thing you are describing.

**Comment by rvazarkar** [comment]
You shouldn't need admin rights for bloodhound.exe...strange. I run it low priv on my system. Usually this issue is fixed by either reloading bloodhound with ctrl + r, or clicking on the URL field and hitting tab to force it to recheck the database status.

**Comment by matchstickboy** [comment]
Thank you both.  I didn't think that running as Admin would be necessary, but gave it a try anyways.  Same result.

I have also now built a Bloodhound environment on a Windows 10 VM.  The installation of Neo4j as a service completed successfully, and the service runs normally.

I am able to log into the Neo4j database and change the initial password.  But when running Bloodhound, I'm still getting a red strike through when hovering over the Login button.

No anti-virus is installed, and Windows Defender has been disabled.  Also have made sure User Account Control has been disabled (just in case).

Is there any debugging or logging that I can enable?  Maybe I can provide more helpful diagnostics that way to see what i am doing wrong here.

Thanks again, and regards.

Chris

**Comment by rvazarkar** [comment]
Can you take a picture of your login window?

**Comment by matchstickboy** [comment]
Hello Rohan,

Please disregard all of this.  This whole time I was not filling in the database URL correctly, so the green connection check mark never appeared.  Once I actually performed this step correctly, I was able to log in and ingest data as hoped.

I am very sorry to have wasted any of your time with this.  Thank you for taking the time to help.

Regards,

Chris
